// A curated set of popular Sherwin-Williams colours. Hex values are approximate screen
// equivalents — always check a physical chip. Any custom colour can also be entered.
export interface Paint { code: string; name: string; hex: string; family: string }

export const SW_PAINTS: Paint[] = [
  // Whites
  { code: 'SW 7008', name: 'Alabaster', hex: '#EDEAE0', family: 'White' },
  { code: 'SW 7005', name: 'Pure White', hex: '#EDECE6', family: 'White' },
  { code: 'SW 7006', name: 'Extra White', hex: '#EEEFEA', family: 'White' },
  { code: 'SW 7004', name: 'Snowbound', hex: '#EDEAE5', family: 'White' },
  { code: 'SW 7012', name: 'Creamy', hex: '#EFE8DB', family: 'White' },
  { code: 'SW 7042', name: 'Shoji White', hex: '#E6DFD3', family: 'White' },
  { code: 'SW 7551', name: 'Greek Villa', hex: '#F0ECE2', family: 'White' },
  { code: 'SW 7757', name: 'High Reflective White', hex: '#F7F7F1', family: 'White' },
  { code: 'SW 7009', name: 'Pearly White', hex: '#E8E3D9', family: 'White' },
  { code: 'SW 7010', name: 'White Duck', hex: '#E5DFD2', family: 'White' },
  { code: 'SW 7036', name: 'Accessible Beige', hex: '#D1C7B8', family: 'Neutral' },
  // Greiges & grays
  { code: 'SW 7029', name: 'Agreeable Gray', hex: '#D1CBC1', family: 'Neutral' },
  { code: 'SW 7015', name: 'Repose Gray', hex: '#CCC9C0', family: 'Neutral' },
  { code: 'SW 7016', name: 'Mindful Gray', hex: '#BCB7AD', family: 'Neutral' },
  { code: 'SW 7017', name: 'Dorian Gray', hex: '#ACA79E', family: 'Neutral' },
  { code: 'SW 7043', name: 'Worldly Gray', hex: '#CFCAC0', family: 'Neutral' },
  { code: 'SW 7044', name: 'Amazing Gray', hex: '#BEB5A9', family: 'Neutral' },
  { code: 'SW 7632', name: 'Modern Gray', hex: '#D6CEC3', family: 'Neutral' },
  { code: 'SW 7031', name: 'Mega Greige', hex: '#ADA296', family: 'Neutral' },
  { code: 'SW 7037', name: 'Balanced Beige', hex: '#C0B2A2', family: 'Neutral' },
  { code: 'SW 6106', name: 'Kilim Beige', hex: '#D7C5AE', family: 'Neutral' },
  { code: 'SW 7506', name: 'Loggia', hex: '#C4B7A5', family: 'Neutral' },
  { code: 'SW 7641', name: 'Colonnade Gray', hex: '#C6C0B6', family: 'Neutral' },
  { code: 'SW 7018', name: 'Dovetail', hex: '#908A83', family: 'Neutral' },
  { code: 'SW 7019', name: 'Gauntlet Gray', hex: '#78736E', family: 'Neutral' },
  { code: 'SW 7048', name: 'Urbane Bronze', hex: '#54504A', family: 'Dark' },
  { code: 'SW 7069', name: 'Iron Ore', hex: '#434341', family: 'Dark' },
  { code: 'SW 6258', name: 'Tricorn Black', hex: '#2F2F30', family: 'Dark' },
  { code: 'SW 7674', name: 'Peppercorn', hex: '#585858', family: 'Dark' },
  { code: 'SW 7076', name: 'Cyberspace', hex: '#44484D', family: 'Dark' },
  { code: 'SW 7020', name: 'Black Fox', hex: '#4F4842', family: 'Dark' },
  { code: 'SW 7064', name: 'Passive', hex: '#CBCCC9', family: 'Neutral' },
  { code: 'SW 7066', name: 'Gray Matters', hex: '#A7A8A2', family: 'Neutral' },
  { code: 'SW 7071', name: 'Gray Screen', hex: '#C6CAC4', family: 'Neutral' },
  // Greens
  { code: 'SW 6204', name: 'Sea Salt', hex: '#CDD2CA', family: 'Green' },
  { code: 'SW 9130', name: 'Evergreen Fog', hex: '#95978A', family: 'Green' },
  { code: 'SW 6208', name: 'Pewter Green', hex: '#5E6259', family: 'Green' },
  { code: 'SW 2851', name: 'Sage Green Light', hex: '#73705E', family: 'Green' },
  { code: 'SW 6178', name: 'Clary Sage', hex: '#ACAD97', family: 'Green' },
  { code: 'SW 6206', name: 'Oyster Bay', hex: '#AEB3A9', family: 'Green' },
  { code: 'SW 6207', name: 'Retreat', hex: '#7A8076', family: 'Green' },
  { code: 'SW 7732', name: 'Lemon Verbena', hex: '#CBC8A0', family: 'Green' },
  { code: 'SW 6188', name: 'Shade-Grown', hex: '#4E5147', family: 'Green' },
  { code: 'SW 6194', name: 'Basil', hex: '#879F84', family: 'Green' },
  { code: 'SW 9129', name: 'Jade Dragon', hex: '#9AA395', family: 'Green' },
  { code: 'SW 6461', name: 'Isle of Pines', hex: '#3D5541', family: 'Green' },
  { code: 'SW 6468', name: 'Hunt Club', hex: '#2A4F43', family: 'Green' },
  { code: 'SW 6186', name: 'Dried Thyme', hex: '#7B8070', family: 'Green' },
  { code: 'SW 6176', name: 'Liveable Green', hex: '#CECEBD', family: 'Green' },
  // Blues
  { code: 'SW 6244', name: 'Naval', hex: '#2F3D4C', family: 'Blue' },
  { code: 'SW 6211', name: 'Rainwashed', hex: '#C2CDC5', family: 'Blue' },
  { code: 'SW 6218', name: 'Tradewind', hex: '#B6C5C1', family: 'Blue' },
  { code: 'SW 7602', name: 'Indigo Batik', hex: '#3E5063', family: 'Blue' },
  { code: 'SW 9177', name: 'Salty Dog', hex: '#234058', family: 'Blue' },
  { code: 'SW 6230', name: 'Rainstorm', hex: '#244653', family: 'Blue' },
  { code: 'SW 6248', name: 'Jubilee', hex: '#C7CBD0', family: 'Blue' },
  { code: 'SW 6251', name: 'Outerbanks', hex: '#899BA8', family: 'Blue' },
  { code: 'SW 9136', name: 'Lullaby', hex: '#CBD4D4', family: 'Blue' },
  { code: 'SW 6239', name: 'Upward', hex: '#BFC9D0', family: 'Blue' },
  { code: 'SW 6242', name: 'Bracing Blue', hex: '#768B9A', family: 'Blue' },
  { code: 'SW 7623', name: 'Cityscape', hex: '#7F8181', family: 'Blue' },
  { code: 'SW 6243', name: 'Distance', hex: '#5F7485', family: 'Blue' },
  { code: 'SW 6495', name: 'Great Falls', hex: '#6C8A8B', family: 'Blue' },
  { code: 'SW 6523', name: 'Denim', hex: '#506B84', family: 'Blue' },
  // Warm colours
  { code: 'SW 9081', name: 'Redend Point', hex: '#AE8E7E', family: 'Warm' },
  { code: 'SW 6047', name: 'Hot Cocoa', hex: '#806257', family: 'Warm' },
  { code: 'SW 7038', name: 'Tony Taupe', hex: '#B1A290', family: 'Warm' },
  { code: 'SW 6108', name: 'Latte', hex: '#BAA185', family: 'Warm' },
  { code: 'SW 6385', name: 'Dover White', hex: '#F0EADC', family: 'White' },
  { code: 'SW 6126', name: 'Navajo White', hex: '#E9DCC6', family: 'Warm' },
  { code: 'SW 9109', name: 'Natural Linen', hex: '#DFD3C3', family: 'Warm' },
  { code: 'SW 6340', name: 'Baked Clay', hex: '#9C5E47', family: 'Warm' },
  { code: 'SW 7587', name: 'Antique Red', hex: '#9F4442', family: 'Warm' },
  { code: 'SW 6328', name: 'Fireweed', hex: '#7B3730', family: 'Warm' },
  { code: 'SW 6318', name: 'Resounding Rose', hex: '#CD8E89', family: 'Warm' },
  { code: 'SW 6309', name: 'Charming Pink', hex: '#EDD3D2', family: 'Warm' },
  { code: 'SW 6022', name: 'Breathless', hex: '#D6C2BE', family: 'Warm' },
  { code: 'SW 6674', name: 'Jonquil', hex: '#F4D59C', family: 'Warm' },
  { code: 'SW 6385', name: 'Dover White', hex: '#F0EADC', family: 'White' },
  { code: 'SW 6119', name: 'Antique White', hex: '#E8DCC6', family: 'Warm' },
  { code: 'SW 6360', name: 'Folksy Gold', hex: '#D19B45', family: 'Warm' },
].filter((p, i, all) => all.findIndex((q) => q.code === p.code) === i);

export const PAINT_FAMILIES = ['All', 'White', 'Neutral', 'Dark', 'Green', 'Blue', 'Warm'];
